language: r
r:
  - devel
sudo: false
cache: packages

warnings_are_errors: false

env:
  global:
  - CRAN: http://cran.rstudio.com

notifications:
  email:
  on_success: true
on_failure: true

after_success:
  - Rscript -e 'library(covr);coveralls()'