---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ceylon

<!-- badges: start -->
<!-- badges: end -->

The goal of ceylon is to plot maps of Sri Lanka.

## Installation

You can install the released version of ceylon from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ceylon")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thiyangt/ceylon")
```
## Example

This is a basic example which shows you how to solve a common problem:

### 0. Country level

```{r example}
library(ceylon)
library(tidyverse)
library(sp)
data(sf_sl_0)
ggplot(sf_sl_0) + geom_sf()
```

### 1. Province level

```{r example1}
data(sf_sl_1)
sf_sl_1
ggplot(sf_sl_1) + geom_sf(mapping = aes(fill = PROVINCE), show.legend = TRUE)
```

### 2. District level

```{r example2}
data(sf_sl_2)
ggplot(sf_sl_2) + geom_sf(mapping = aes(fill = DISTRICT), show.legend = FALSE)
```

### 3. Divisional secretariat

```{r example3}
data(sf_sl_3)
ggplot(sf_sl_3) + geom_sf()
```

